### ISSUE TITLE
Implement a way to attach child builders to a parent builder

### ISSUE THREAD

**Issue by etkirsch** [etkirsch/Procedural-Builder#4]
For instance, say the origin node is going to chain to some node down the road... There should be a method in origin node to attach a specific builder for that desired child node.

```C#
dynamic solarSystemBuilder = new SolarSystemBuilder();
dynamic continentBuilder = new ContinentBuilder();
solarSystemBuilder.WithChainedBuilder(continentBuilder);
```

Or something. The question will be how the system determines the builders to use. Perhaps a collection of attached builders?

**Comment by NullVoxPopuli** [comment]
Math.Rand

**Comment by etkirsch** [comment]
...................wat?

**Comment by etkirsch** [comment]
Rudimentary implementation in most recent commit. Probably need to wrap ProcedurallyGenerate() in another method so that I can automate the .SetChainedBuilders() method.
